### ISSUE TITLE
突然就有了工大自己的镜像站哈哈，支持一下

### ISSUE THREAD

**Issue by geekhch** [hitlug/mirror-web#43]
想问问镜像站是面向外网开放的吗？带宽这些情况如何呢？有没有长期运行的计划？有没有交流群？
谢谢~
另外希望完善下各种镜像的配置生成，anaconda等。

**Comment by billchenchina** [comment]
1. 自 2020 年 6 月起面向外网开放；
2. 目前服务器光纤接入教育网，接口速率 20Gbps；
3. 目前镜像站由计算学部 Linux 开源学生科创俱乐部（简称 HITLUG）维护，尽可能长期运行；
4. 可以从 <https://lug.hit.edu.cn/> 找到 QQ 群号，目前没有其他群。
